name: 08 - Outputs Workflow 2

on:
  schedule:
    - cron: "0 6 * * MON-FRI" # Runs at 6:00 UTC
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "test=hello" >> $GITHUB_OUTPUT
    - id: step2
      run: echo "test=world" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    # Wait from the job1 to be completed before starting job2
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
    - run: echo "Goodbye"

  job4:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        id: xyz
        run: echo "ip-address=$(curl -s ifconfig.me)" >> $GITHUB_OUTPUT
      - name: step-2
        run: echo "${{ steps.xyz.outputs.ip-address }}"
      - name: step-3
        run: |
          echo '{
            "ip-address": "${{ steps.xyz.outputs.ip-address }}"
          }'
